# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-14 08:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180614_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 8, 26, 0, 653410, tzinfo=utc)),
        ),
    ]
